import { Image } from "expo-image";
import { StatusBar } from "expo-status-bar";
import { Plus, Sparkles } from "lucide-react-native";
import { useState, useEffect } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View, Alert, RefreshControl } from "react-native";
import { useRouter } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import { useCallback } from "react";
import ForgeCourseModal from "../../components/ForgeCourseModal";
import QuestCard from "../../components/QuestCard";
import QuestPlaceholder from "../../components/QuestPlaceholder";
import { useEnrolledCourses } from "../../hooks/useEnrolledCourses";
import { useUserData } from "../../hooks/useUserData";
import { forgeCourse } from "../../utils/course";
import { requestNotificationPermissions, sendLocalNotification } from "../../utils/notifications";

export default function QuestsScreen() {
  const router = useRouter();
  const { userData, isLoading: isUserLoading, refetch: refetchUser } = useUserData();
  const { enrolledCourses, isLoading: isCoursesLoading, refetch: refetchCourses } = useEnrolledCourses();
  const [isModalVisible, setIsModalVisible] = useState(false);
  const [pendingTopics, setPendingTopics] = useState<string[]>([]);
  const [refreshing, setRefreshing] = useState(false);

  const onRefresh = useCallback(async () => {
    setRefreshing(true);
    await Promise.all([refetchUser(), refetchCourses()]);
    setRefreshing(false);
  }, [refetchUser, refetchCourses]);

  useEffect(() => {
    requestNotificationPermissions();
  }, []);

  const handleForgeJourney = async (topic: string, difficulty: string) => {
    if (!userData?.id) {
      Alert.alert("Error", "User data not loaded. Please try again.");
      return;
    }

    // Add to pending topics immediately
    setPendingTopics(prev => [...prev, topic]);
    
    // Show immediate feedback message
    Alert.alert(
      "The Forge is Lit! 🔥",
      "Your course is being generated by our AI spirits. You'll find it under Active Missions in a moment."
    );

    // Fire and forget (don't await the whole process in the UI return)
    (async () => {
      try {
        await forgeCourse(topic, difficulty, userData.id);
        setPendingTopics(prev => prev.filter(t => t !== topic));
        await Promise.all([
          refetchCourses(),
          refetchUser()
        ]);
        await sendLocalNotification(
          "Journey Forged! ⚒️",
          `Your quest for "${topic}" is ready for you to explore.`
        );
      } catch (error) {
        console.error("Failed to forge journey:", error);
        setPendingTopics(prev => prev.filter(t => t !== topic));
        Alert.alert("Forge Failed", `The AI spirits failed to craft "${topic}". Please try again.`);
      }
    })();
  };

  const formatNumber = (num: number) => num.toLocaleString();

  return (
    <View style={styles.container}>
      <StatusBar style="light" />
      <SafeAreaView style={styles.safeArea} edges={["top"]}>
        {/* Atmosphere */}
        <View style={[styles.glow, styles.glowTop]} />
        <View style={[styles.glow, styles.glowBottom]} />

        <ScrollView
          contentContainerStyle={styles.scrollContent}
          showsVerticalScrollIndicator={false}
          refreshControl={
            <RefreshControl refreshing={refreshing} onRefresh={onRefresh} tintColor="#10b981" />
          }
        >
          {/* Header Section */}
          <View style={styles.header}>
            <View>
              <Text style={styles.label}>EPIC MISSIONS</Text>
              <Text style={styles.title}>Quest Log</Text>
            </View>
            <View style={styles.statsContainer}>
              <View style={styles.statItem}>
                <Image source={require("../../assets/images/gem.png")} style={styles.statIcon} />
                <Text style={styles.statText}>{isUserLoading ? "..." : formatNumber(userData?.xp || 0)}</Text>
              </View>
            </View>
          </View>

          {/* Forge New Journey (Create Course CTA) */}
          <Pressable 
            style={({ pressed }) => [styles.forgeCard, pressed && styles.cardPressed]}
            onPress={() => setIsModalVisible(true)}
          >
            <View style={styles.forgeContent}>
              <View style={styles.forgeIconContainer}>
                <Image source={require("../../assets/images/scroll.png")} style={styles.forgeIcon} />
                <View style={styles.sparkleContainer}>
                  <Sparkles size={16} color="#fbbf24" fill="#fbbf24" />
                </View>
              </View>
              <View style={styles.forgeTextContainer}>
                <Text style={styles.forgeTitle}>Forge New Journey</Text>
                <Text style={styles.forgeSubtitle}>Use AI to craft a custom learning path</Text>
              </View>
              <View style={styles.plusCircle}>
                <Plus size={24} color="#ffffff" />
              </View>
            </View>
          </Pressable>

          {/* Active Missions Section */}
          <View style={styles.sectionHeader}>
            <Text style={styles.sectionTitle}>ACTIVE MISSIONS</Text>
            <Text style={styles.sectionBadge}>{enrolledCourses.length + pendingTopics.length}</Text>
          </View>

          {isCoursesLoading ? (
            <ActivityIndicator size="large" color="#a855f7" style={{ marginVertical: 40 }} />
          ) : (enrolledCourses.length > 0 || pendingTopics.length > 0) ? (
            <>
              {pendingTopics.map((topic, index) => (
                <QuestPlaceholder key={`pending-${index}`} topic={topic} />
              ))}
              {enrolledCourses.map((course) => (
                <QuestCard
                  key={course.id}
                  title={course.title}
                  category={course.category}
                  progress={course.progress}
                  totalChapters={course.totalChapters}
                  lastAccessed={new Date(course.lastAccessedAt).toLocaleDateString()}
                  onPress={() => router.push({ pathname: ("/course/[id]" as any), params: { id: course.id as any } })}
                />
              ))}
            </>
          ) : (
            <View style={styles.emptyState}>
              <Text style={styles.emptyText}>No active missions. Start a new one!</Text>
            </View>
          )}

          <ForgeCourseModal
            isVisible={isModalVisible}
            onClose={() => setIsModalVisible(false)}
            onForge={handleForgeJourney}
            userData={userData}
          />

          <View style={{ height: 100 }} />
        </ScrollView>
      </SafeAreaView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#0b0c15",
  },
  safeArea: {
    flex: 1,
  },
  glow: {
    position: "absolute",
    width: 300,
    height: 300,
    borderRadius: 150,
    opacity: 0.15,
  },
  glowTop: {
    top: -50,
    left: -100,
    backgroundColor: "#10b981",
  },
  glowBottom: {
    bottom: 100,
    right: -100,
    backgroundColor: "#a855f7",
  },
  scrollContent: {
    padding: 24,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    marginBottom: 32,
  },
  label: {
    fontSize: 11,
    fontWeight: "900",
    color: "#10b981",
    letterSpacing: 2,
    marginBottom: 4,
  },
  title: {
    fontSize: 32,
    fontWeight: "900",
    color: "#ffffff",
    letterSpacing: 1,
  },
  statsContainer: {
    flexDirection: "row",
    gap: 12,
  },
  statItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#1e293b",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    gap: 6,
    borderWidth: 1,
    borderColor: "#334155",
  },
  statIcon: {
    width: 16,
    height: 16,
  },
  statText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "900",
  },
  forgeCard: {
    backgroundColor: "#10b98115",
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: "#10b98144",
    marginBottom: 40,
    shadowColor: "#10b981",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 15,
  },
  cardPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.98 }],
  },
  forgeContent: {
    flexDirection: "row",
    alignItems: "center",
  },
  forgeIconContainer: {
    width: 60,
    height: 60,
    borderRadius: 20,
    backgroundColor: "#10b98122",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 16,
  },
  forgeIcon: {
    width: 32,
    height: 32,
  },
  sparkleContainer: {
    position: "absolute",
    top: -4,
    right: -4,
  },
  forgeTextContainer: {
    flex: 1,
  },
  forgeTitle: {
    fontSize: 18,
    fontWeight: "900",
    color: "#f1f5f9",
    marginBottom: 4,
  },
  forgeSubtitle: {
    fontSize: 12,
    color: "#94a3b8",
  },
  plusCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#10b981",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#10b981",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 10,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: "900",
    color: "#94a3b8",
    letterSpacing: 2,
  },
  sectionBadge: {
    backgroundColor: "#1e293b",
    color: "#ffffff",
    fontSize: 11,
    fontWeight: "900",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
    overflow: "hidden",
  },
  emptyState: {
    padding: 40,
    alignItems: "center",
    backgroundColor: "#111827",
    borderRadius: 24,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "#1e293b",
    marginBottom: 40,
  },
  emptyText: {
    color: "#64748b",
    fontSize: 14,
    fontWeight: "600",
  },
});
